### ISSUE TITLE
Cannot have a first name below 5 characters in registration

### ISSUE THREAD

**Issue by TheoCGaming** [VertisanPRO/PterodactylRegister#1]
### Current Behavior

If I input "Ken" for example into the First Name field, it shows an error saying that the first name must be 5 characters or more.
### Expected Behavior

The name "Ken" is accepted as the first name.
### Steps to Reproduce

1.    Attempt to register.
2.    Input all needed info, but with a 3-letter first name (or last name). May also apply with other languages.
3.    The error shows.
### Extra Notes

This may show as "Working as Intended", but I can't register because of it. If it isn't fixed, I'll never be able to register with my real name or I'll only be able to register through panel invites.

**Comment by PadowYT2** [comment]
Not a bug, [here you can change minimum](https://github.com/GIGABAIT-Official/PterodactylRegister/blob/main/Registration%20Module%20Files/app/Http/Controllers/Auth/RegisterController.php#L43-L45). This is not recommended as bots mostly use 3 letters.
